### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by folkertvanheusden** [AGProjects/python3-otr#3]
Hi,

Can you please provide documentation and/or examples?

**Comment by adigeo** [comment]
https://github.com/AGProjects/python-sipsimple/blob/master/sipsimple/streams/msrp/chat.py

https://github.com/AGProjects/blink-qt/blob/master/blink/chatwindow.py

https://github.com/AGProjects/blink-cocoa/blob/master/ChatController.py

https://github.com/AGProjects/sipclients3/blob/master/sip-session3

**Comment by folkertvanheusden** [comment]
With zero comments in them these examples are, imho, not usable as documentation.

**Comment by adigeo** [comment]
True, but working examples written by several developers are also good.

It is an open source project, feel free to contribute ewith documetation!
